### ISSUE TITLE
Unable to download toolchain

### ISSUE THREAD

**Issue by gfcwfzkm** [StrongTheDev/avr-utils#1]
Hi

The extension seems to be detecting an AVR project correctly, but when I attempt to download the toolchain, it seems to be failing.

It creates an "AVR Utils/toolchain" folder in whatever path I choose, but both of these folders are empty despite displaying the message "toolchain downloaded".

It must be downloading something, as the network usage from VSCode goes up during the moment - perhaps failing to unzip it?

**Comment by StrongTheDev** [comment]
Thanks for mentioning this issue, I'll get to work to check it as soon as possible.

Perhaps the "tar" node module doesn't work on windows, as i made this extension on linux (since there's no Microchip studio for linux).
Let me download the extension on my windows machine and test things out. Perhaps if you are not using Windows, let me know.

**Comment by StrongTheDev** [comment]
Hello, I have fixed this issue as well. Thanks for the useful feedback. Happy coding! Will update within 24 hours.
