### ISSUE TITLE
in "Select AVR device" not found AT90USB647

### ISSUE THREAD

**Issue by SeyranGrig** [StrongTheDev/avr-utils#3]
I have installed the latest version of Toolchain for AVR 3.7.0 and cannot select AT90USB647 from the available devices. Is it possible to fix this error?

**Comment by StrongTheDev** [comment]
I'll have a look into it soon.

**Comment by StrongTheDev** [comment]
Updated it. Happy coding!

**Comment by SeyranGrig** [comment]
Problems after update

![2024-04-04_08-20-06](https://github.com/DanielHuey/avr-utils/assets/88644590/c2cec5c8-094f-45af-8052-a8d72b22c9d7)

![2024-04-04_08-20-23](https://github.com/DanielHuey/avr-utils/assets/88644590/7232c5cc-7e06-4ebc-af92-31234b56aa4e)

And the microcontroller selection dialog is missing

**Comment by StrongTheDev** [comment]
Okay I've worked on it, however, you should have opened a new issue instead of reusing this closed issue 🙂. It will help keep issues organized such that I can tag the issue separately when writing documentation (e.g fixed issue [#3](https://github.com/DanielHuey/avr-utils/issues/3) for example).

Anyway, please open VSCode and let the extension update, then let me know if it is fixed now.
